JobId=1113691 JobName=script.sh
   UserId=kanderer29(4373) GroupId=macke(4017) MCS_label=N/A
   Priority=62889 Nice=0 Account=macke QOS=normal
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:20 TimeLimit=2-00:00:00 TimeMin=N/A
   SubmitTime=2022-01-11T11:25:47 EligibleTime=2022-01-11T11:25:47
   AccrueTime=2022-01-11T11:25:48
   StartTime=2022-01-11T11:25:48 EndTime=2022-01-13T11:25:48 Deadline=N/A
   PreemptEligibleTime=2022-01-11T11:26:48 PreemptTime=None
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2022-01-11T11:25:48
   Partition=cpu-long AllocNode:Sid=bg-slurmb-login1:13969
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=slurm-cpu-hm-3
   BatchHost=slurm-cpu-hm-3
   NumNodes=1 NumCPUs=64 NumTasks=1 CPUs/Task=64 ReqB:S:C:T=0:0:*:*
   TRES=cpu=64,mem=50G,node=1,billing=11
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=64 MinMemoryNode=50G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/script.sh
   WorkDir=/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code
   StdErr=/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/hostname_1113691.err
   StdIn=/dev/null
   StdOut=/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/hostname_1113691.out
   Power=
   MailUser=k.anderer@t-online.de MailType=END
   NtasksPerTRES:0

new experiment
current working path: /mnt/qb/work/macke/kanderer29
3
params size torch.Size([2, 3])
3
params size torch.Size([3])
3 params are investigated
joblib will run over 1 jobs
Loading custom mechanism files from /home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/hnn_core/mod/x86_64/.libs/libnrnmech.so
Building the NEURON model
[Done]
running trial 1 on 1 cores
Simulation time: 0.03 ms...
Simulation time: 10.0 ms...
Simulation time: 20.0 ms...
Simulation time: 30.0 ms...
Simulation time: 40.0 ms...
Simulation time: 50.0 ms...
Simulation time: 60.0 ms...
Simulation time: 70.0 ms...
Simulation time: 80.0 ms...
Simulation time: 90.0 ms...
Simulation time: 100.0 ms...
Simulation time: 110.0 ms...
Simulation time: 120.0 ms...
Simulation time: 130.0 ms...
Simulation time: 140.0 ms...
Simulation time: 150.0 ms...
Simulation time: 160.0 ms...


--------------------------------------------------------------------------------
LokyProcess-3566 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3569 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3578 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3570 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3573 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3577 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3579 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3576 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-3581 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------
