Warning: no DISPLAY environment variable.
--No graphics will be displayed.
Traceback (most recent call last):
  File "investigating_summary_features.py", line 136, in main
    theta = torch.load('results/{}/step1/thetas.pt'.format(experiment_name))
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/eval_features6/step1/thetas.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "investigating_summary_features.py", line 350, in <module>
    main(sys.argv[1:])
  File "investigating_summary_features.py", line 144, in main
    num_workers=num_workers
  File "/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/utils/inference.py", line 70, in run_sim_theta_x
    simulator_stats, prior = prepare_for_sbi(simulation_wrapper, prior)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/sbi/utils/user_input_checks.py", line 498, in prepare_for_sbi
    simulator = process_simulator(simulator, prior, prior_returns_numpy)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/sbi/utils/user_input_checks.py", line 368, in process_simulator
    assert isinstance(user_simulator, Callable), "Simulator must be a function."
AssertionError: Simulator must be a function.
