Warning: no DISPLAY environment variable.
--No graphics will be displayed.
Traceback (most recent call last):
  File "sequential_inference.py", line 126, in main
    file_writer = torch.load('results/{}/class.pt'.format(experiment_name))
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/Sequential_3_params/class.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sequential_inference.py", line 333, in <module>
    main(sys.argv[1:])
  File "sequential_inference.py", line 146, in main
    os.mkdir('results/{}/step1'.format(experiment_name))
FileNotFoundError: [Errno 2] No such file or directory: 'results/Sequential_3_params/step1'
