Warning: no DISPLAY environment variable.
--No graphics will be displayed.
Traceback (most recent call last):
  File "ERP_sim_inf_multi_round.py", line 318, in <module>
    main(sys.argv[1:])
  File "ERP_sim_inf_multi_round.py", line 225, in main
    trace = pd.read_csv('data/ERPYes3Trials/dpl.txt', sep='\t', header=None, dtype= np.float32)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/macke/kanderer29/.conda/envs/sbi/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/ERPYes3Trials/dpl.txt'
