Warning: no DISPLAY environment variable.
--No graphics will be displayed.
Traceback (most recent call last):
  File "investigating_summary_features.py", line 132, in main
    theta = torch.load('results/{}/step1/thetas.pt'.format(experiment_name))
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/eval_features7/step1/thetas.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "investigating_summary_features.py", line 346, in <module>
    main(sys.argv[1:])
  File "investigating_summary_features.py", line 140, in main
    num_workers=num_workers
  File "/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/utils/inference.py", line 76, in run_sim_theta_x
    num_workers=num_workers,
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/sbi/inference/base.py", line 550, in simulate_for_sbi
    simulator, theta, simulation_batch_size, num_workers, show_progress_bar
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/site-packages/sbi/simulators/simutils.py", line 50, in simulate_in_batches
    if num_workers > 1:
TypeError: '>' not supported between instances of 'str' and 'int'
